### PR TITLE
Add full responsiveness

### LINKED ISSUE #1: Make application responsive

### PR DESCRIPTION
**Pull request by Muz4mmil**
Resolves #1 
Closes #1 
Hey @RishabhJain0721 , I am doing a PR directly to master branch. Kindly check and Merge it under `hacktoberfest` and `hacktoberfest-accepted` tags and labels.

### CODE REVIEW

**Comment by Muz4mmil** [comment]
Screenshot_20231029-132508_Chrome

@RishabhJain0721 Hello bro,
As soon as you merged the PR, it shows not accepted in hacktoberfest page.
Do you have any idea??
Also, can you try adding `hacktoberfest-accepted` label too...
It was a tough work taking that subject pane to nav menu, I want this issue to get counted

**Comment by RishabhJain0721** [comment]
I have merged your PR.
*A tip* : Don't push any code having some API key directly. Use a .env file to manage it.

**Comment by Muz4mmil** [comment]
> I have merged your PR. _A tip_ : Don't push any code having some API key directly. Use a .env file to manage it.

Yeah thanks for merging.
But I just forked your repo, cloned, made changes and created PR. I didn't touched any api or your Firebase config

**Comment by RishabhJain0721** [comment]
@Muz4mmil Hello bro
I am sorry you are facing this.
I have added all required labels, don't know why it's happening.

**Comment by RishabhJain0721** [comment]
> > I have merged your PR. _A tip_ : Don't push any code having some API key directly. Use a .env file to manage it.
> 
> Yeah thanks for merging. But I just forked your repo, cloned, made changes and created PR. I didn't touched any api or your Firebase config

It was in your commit history so I assume it was done by some mistake. Alright now I have changed it.

**Comment by Muz4mmil** [comment]
> @Muz4mmil Hello bro I am sorry you are facing this. I have added all required labels, don't know why it's happening.

Uhh okay no issues,
By the way how's the app now?
Do you want any changes?

Also note that, it is not realtime responsive, I mean if you want to check the responsiveness, you have to reload the page every time you change the screen ( that's not an issue I guess )

**Comment by RishabhJain0721** [comment]
> > @Muz4mmil Hello bro I am sorry you are facing this. I have added all required labels, don't know why it's happening.
> 
> Uhh okay no issues, By the way how's the app now? Do you want any changes?
> 
> Also note that, it is not realtime responsive, I mean if you want to check the responsiveness, you have to reload the page every time you change the screen ( that's not an issue I guess )

It's definitely looking better then before. That sidebar is really nice. 
I don't want any changes as of now. 
That's not a big issue, can be ignored.

Thanks for contributing. 👍🏻

**Comment by Muz4mmil** [comment]
Hey @RishabhJain0721 
Now the PR is getting counted, I don't know how 😂.
Thanks for supporting and sorry for inconvenience, I am new to Open source and still learning how stuff works.

**Pull request merged**
